# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ChocolateOBJCSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ChocolatePlatform-SDK-Core', '~> 2.11.2'
  pod 'ChocolatePlatform-SDK-AdColony', '~> 2.0'
  pod 'ChocolatePlatform-SDK-AppLovin', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Baidu', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Facebook', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Flurry', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Googleadmob', '~> 1.0'
  pod 'ChocolatePlatform-SDK-Mopub', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Tapjoy', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Unity', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Vungle', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Amazon', '~> 1.0'
  pod 'ChocolatePlatform-SDK-Google', '~> 2.3'
end
